#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Adapt absolute path to relative path in order to allow YNH install in subdir
indexhtml="$install_dir/index.html"
indexcss=$(find $install_dir/assets -name "index-*.css" -type f)
indexjs=$(du -hs $install_dir/assets/* | sort -hr | cut -f2 | grep -m2 index-.*js$ | tail -n1) #second heavier file whose filename contains "index-" and ends with ".js" (what is in between is a different random string at each new build)
ynh_replace_string --match_string="__YNH_SUBDIR_PATH__" --replace_string="$path" --target_file=$indexhtml
ynh_replace_string --match_string="https://cinny.in" --replace_string="$domain$path" --target_file=$indexhtml
ynh_replace_string --match_string="__YNH_SUBDIR_PATH__" --replace_string="$path" --target_file=$indexcss
ynh_replace_string --match_string="__YNH_SUBDIR_PATH__" --replace_string="$path" --target_file=$indexjs

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# CINNY CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Cinny..." --weight=1

# Copy over the Cinny configuration file
ynh_add_config --template="../conf/cinny.json" --destination="$install_dir/config.json"

# Fix any permissions in the install dir
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
