#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Adapt absolute path to relative path in order to allow YNH install in subdir
indexhtml="$install_dir/index.html"
indexjs=$(du -hs "$install_dir/assets/*" | sort -hr | cut -f2 | grep -m1 "^index-.*js$") #heavier file whose filename starts with "index-" and ends with ".js". What is in between is a different random string at each new build
ynh_replace_special_string --match_string="/assets" --replace_string="./assets" --target_file=$indexhtml
ynh_replace_special_string --match_string="/manifest.json" --replace_string="./manifest.json" --target_file=$indexhtml
ynh_replace_string --match_string="cinny.in/?" --replace_string="$domain$path" --target_file=$indexhtml
ynh_replace_special_string --match_string='const t=`${zi("/")}/config.json`;' --replace_string='const t=`${zi("./")}/config.json`;' --target_file=$indexjs

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# CINNY CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Cinny..." --weight=1

# Copy over the Cinny configuration file
ynh_add_config --template="../conf/cinny.json" --destination="$install_dir/config.json"

# Fix any permissions in the install dir
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
