#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if [[ "$path" != "/" ]]; then
    ynh_die "Installing Cinny on a subpath is not supported anymore (see https://github.com/YunoHost-Apps/cinny_ynh/pull/66)"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep="config.json"

# Adapt absolute path to relative path in order to allow YNH install in subdir
indexhtml="$install_dir/index.html"
indexjs=$(du -hs "$install_dir/assets/*" | sort -hr | cut -f2 | grep -m1 "^index-.*js$") #heavier file whose filename starts with "index-" and ends with ".js". What is in between is a different random string at each new build
ynh_replace_special_string --match_string="/assets" --replace_string="./assets" --target_file=$indexhtml
ynh_replace_special_string --match_string="/manifest.json" --replace_string="./manifest.json" --target_file=$indexhtml
ynh_replace_string --match_string="cinny.in/?" --replace_string="$domain$path" --target_file=$indexhtml
ynh_replace_special_string --match_string='const t=`${zi("/")}/config.json`;' --replace_string='const t=`${zi("./")}/config.json`;' --target_file=$indexjs

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
